### ISSUE TITLE
Metadata/Styling

### ISSUE THREAD

**Issue by lkwalke4** [kartoza/least-cost-electrification-somaliland#8]
Hi @seabilwe - can you please use this space to provide regular updates on metadata capture and styling as things progress? Currently, we'll need to look at all of the following:

**Metadata**
Overall, we need to ensure that metadata is as complete as possible. Please ensure that the following mandatory information (as specified by the inception report) is populated for every layer - it is not currently.
-Name/Title
-Abstract describing data purpose
-Date of publication
-Licensing
-Owner

- [x] Additionally, @seabilwe can you check on the progress of metadata collection from the Government via the OneDrive sheet that Nicolina sent to the Government please?

**Styling**
Overall, we need to make sure that layers are clear in their meaning and ensure that legends are informative. Below I've highlighted some issues, but we need to go through everything thoroughly as we move towards the final product.

- [x] -For the nightime lights layer, @seabilwe could you see if you could continue massaging this layer to highlight where there is actual data, while reducing the visual impact of the "no data" areas?

- [ ] -Similarly, could you do some things with breaks, etc to make this data more visually engaging please?

![image](https://user-images.githubusercontent.com/18428984/134044610-13f3d97c-c0ab-4a82-a42b-2881024b8ab5.png)

- [x] -This is a slightly odd layer - what exactly is an "area" of worship?

![image](https://user-images.githubusercontent.com/18428984/134045845-6b7be4ee-44f0-41b3-acd9-d505b5c96d40.png)

- [x] -What is the difference between these layers, and should they really be separate?

![image](https://user-images.githubusercontent.com/18428984/134046074-30ae416f-65b3-4ffc-8162-34ec4f97cd2a.png)

- [x] -Could you please choose a different styling for this layer that is more informative? It is a bit chaotic at a small scale.

![image](https://user-images.githubusercontent.com/18428984/134046200-873b2925-23b2-4e2c-a6a6-ad5eef74dafc.png)

- [x] -Could you please add more informative legend information to this layer, to interpret what the numbers mean?

![image](https://user-images.githubusercontent.com/18428984/134046679-aaa1f96c-d32a-423e-a9a1-59c48162c996.png)

- [x] -Simlarly, can you please go through all legends and ensure that important information (such as what measurement wind speed is in for this layer, for example - miles per hours, metres per hours, knots per hours, etc) is reflected in the legends and/or metadata as appropriate?

![image](https://user-images.githubusercontent.com/18428984/134047035-d473153a-d19d-46e7-92a0-2f70b6644a84.png)

- [x] -I am unclear on exactly what this layer is showing. Percentage of specific population centers that are rural nomads, based on what the legend is telling me? Don't rural nomads exist outside population centers? Perhaps work on making this layer cleared on what it is showing.

![image](https://user-images.githubusercontent.com/18428984/134047321-2e44a2e4-8213-4102-b4fd-ef243292cee7.png)

- [x] -We need to show population density and distribution per the inception report. However, we have several population layers and none of them are really formatted to show density or distribution in a good visual way. Could you please determine which one should be used (world bank vs GoSL population clusters) and make sure that the layers have a useful legend and are formatted to show both density and distribution?

![image](https://user-images.githubusercontent.com/18428984/134048604-a3e03bf4-8c90-4804-af72-c9d916d6b581.png)

- [x] -We need to show poverty, if the Government provides it. Otherwise, I suppose that we could format the GDP information, or similar data, to reflect areas of high poverty.

**Missing Layers**

- [ ] @seabilwe do we have any updates on data collection on the part of the Government? I notice that we're missing (per the inception report):

-Layers on 33kv-66kv electric
-Service transformers

**Comment by seabilwe** [comment]
Hi @lkwalke4 

**Tasks in-progress**
- [ ]  Additionally, @seabilwe can you check on the progress of metadata collection from the Government via the OneDrive sheet that Nicolina sent to the Government, please?
   - The Somaliland team has not done any edits to the file yet, more especially to the layers that do not have links (not already in the platform). This includes the missing layers mentioned above. 
- [ ] do we have any updates on data collection on the part of the Government? 
  - Not at the moment no, I will schedule an email that will remind the government to not forget about the datasets needed.

- [ ] Similarly, could you do some things with breaks, etc to make this data more visually engaging, please?
    - I have downloaded the original global layer from DRYAD again and I going to clip it and see if gives similar results I am getting with the current one on the platform.
 

- [x] We need to show population density and distribution per the inception report. However, we have several population layers and none of them are really formatted to show density or distribution in a good visual way. Could you please determine which one should be used (world bank vs GoSL population clusters) and make sure that the layers have a useful legend and are formatted to show both density and distribution?
   - @meomancer please indicate which layer between the two are you using for the SEP:
       -  https://somaliland.gep.kartoza.com/layers/geonode_data:geonode:Somaliland_WBPopulation_clusters_clipped0
       -  https://somaliland.gep.kartoza.com/layers/GoSL_pop_PB:geonode:GoSL_pop_PB

- [x] We need to show poverty, if the Government provides it. Otherwise, I suppose that we could format the GDP information, or similar data, to reflect areas of high poverty.
   - the osm population center layer has a field for poverty rate: https://somaliland.gep.kartoza.com/layers/geonode_data:geonode:somaliland_pop_centers_osm. I am trying to see if I cannot rasterize it and see what we can get, and use it as a backup if the Government does not supply the layer.

**7 Tasks completed so far**
- [x] Nighttime lights styling: https://somaliland.gep.kartoza.com/layers/somaliland_nighttime_lights_20200:geonode:somaliland_nighttime_lights_20200
- [x] Places of worship: https://somaliland.gep.kartoza.com/layers/geonode_data:geonode:somaliland_osm_pofw_areas
- [x] Merged power lines: https://somaliland.gep.kartoza.com/layers/geonode_data:geonode:somaliland_powerline
- [x] Education facilities:https://somaliland.gep.kartoza.com/layers/geonode_data:geonode:somaliland_unicef_education_facilities
- [x] Windspeed: https://somaliland.gep.kartoza.com/layers/somaliland_windspeed:geonode:somaliland_windspeed
- [x] Landcover: https://somaliland.gep.kartoza.com/layers/somaliland_landcover:geonode:somaliland_landcover

**Comment by meomancer** [comment]
hi @seabilwe 

> @meomancer please indicate which layer between the two are you using for the SEP:
https://somaliland.gep.kartoza.com/layers/geonode_data:geonode:Somaliland_WBPopulation_clusters_clipped0
https://somaliland.gep.kartoza.com/layers/GoSL_pop_PB:geonode:GoSL_pop_PB

Currently SEP is using
https://somaliland.gep.kartoza.com/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.resource.ResourceConfigurationPage?5&name=Somaliland_WBPopulation_clusters_clipped&wsName=geonode
Which is "Somaliland_WBPopulation_clusters_clipped" in geoserver (i think we can delete Somaliland_WBPopulation_clusters_clipped0)?

And SEP does not use https://somaliland.gep.kartoza.com/layers/GoSL_pop_PB:geonode:GoSL_pop_PB

**Comment by seabilwe** [comment]
Thanks @meomancer

**Comment by lkwalke4** [comment]
Seabilwe, 

Please see my comments on the current styling and metadata status below:

![image](https://user-images.githubusercontent.com/18428984/136287552-2e3f5b9c-018e-4a8b-b5db-c74aae7f2b8d.png)
![image](https://user-images.githubusercontent.com/18428984/136287602-77b56cc4-cbdd-4bcc-a244-b69f952fd289.png)

Are you still working with this layer, or is this it in its final stage?

![image](https://user-images.githubusercontent.com/18428984/136287753-cff39ce1-df24-4a96-b7b5-e143b58992f2.png)
![image](https://user-images.githubusercontent.com/18428984/136287836-3f1feb0a-612a-4fa7-94a3-cc4779e84361.png)


One of my requests is for more informative legends to be used. The first picture is the nighttime lights layer and I feel that the legend isn't informative. Do we have the ability to alter this legend to tell the user what the numbers represent? And add better labels? The second legend is a better example, though I could like the legend title to be formatted more appropriately.

![image](https://user-images.githubusercontent.com/18428984/136288017-9d388a29-6882-46d5-afa4-5e3b60c8a604.png)

What is the difference between these two layers?

![image](https://user-images.githubusercontent.com/18428984/136288143-2ee47fb4-b836-453d-890f-35c879f46d5b.png)

This doesn't seem to be a very useful layer. What is an apron for a transportation area?

![image](https://user-images.githubusercontent.com/18428984/136288229-6d8353a8-1537-49ba-b885-a8d84b02a178.png)

The cartography is somewhat better, however can we update the layer preview as it still reflects the previous cartography?

![image](https://user-images.githubusercontent.com/18428984/136288519-d471243b-3303-4ebe-be00-5db840d5244a.png)

This layer represents the issues we still have. Uninformative legends (what is hydro potential? how is it defined?) and missing metadata (we must have licensing information on each layer).

I've put a call on the calendar for us to chat through the cartography and metadata on Monday! Talk to you then!
